// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx_8bPKNDYF6ku588zOwTXRoEf8qwqeGY',
    appId: '1:946504050758:web:b045beecc81f7f7b95c247',
    messagingSenderId: '946504050758',
    projectId: 'thproject-8fa04',
    authDomain: 'thproject-8fa04.firebaseapp.com',
    storageBucket: 'thproject-8fa04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVQ3uq129qh_qUgzIz25tRoNWCcpRgMr0',
    appId: '1:946504050758:android:85540f38142af04195c247',
    messagingSenderId: '946504050758',
    projectId: 'thproject-8fa04',
    storageBucket: 'thproject-8fa04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGXUqWnxhexKEu0pwrZYPPFdGEJ9_cC9M',
    appId: '1:946504050758:ios:266e6ffc9952954895c247',
    messagingSenderId: '946504050758',
    projectId: 'thproject-8fa04',
    storageBucket: 'thproject-8fa04.appspot.com',
    iosClientId: '946504050758-lmrsvhsk21f86bb33ollssr2ukgrn897.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightbooking12thproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGXUqWnxhexKEu0pwrZYPPFdGEJ9_cC9M',
    appId: '1:946504050758:ios:266e6ffc9952954895c247',
    messagingSenderId: '946504050758',
    projectId: 'thproject-8fa04',
    storageBucket: 'thproject-8fa04.appspot.com',
    iosClientId: '946504050758-lmrsvhsk21f86bb33ollssr2ukgrn897.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightbooking12thproject',
  );
}
